### PR TITLE
Add Cryptozoologist.name to the project

### PR DESCRIPTION
**Pull request by PrimeTimeTran**
Any changes you might want to the code thus far? I'm not sure what the second part of the name was supposed to be so I just added some occupations from a dictionary I found. Couldn't think of how the three examples that you gave were related.
Here's my Bundle Console.
screen shot 2017-09-17 at 7 15 48 pm

### CODE REVIEW

**Comment by PrimeTimeTran** [comment]
#23

**Comment by chug2k** [comment]
Wow this is great work! It needs a review @feministy  ;)

**Comment by chug2k** [comment]
Wow I really wish I could use a `.name` feature... ;) @feministy

**Comment by PrimeTimeTran** [comment]
@feministy would you be able to get some time in the near future to check out this PR and update it? I would really appreciate it. Thanks for your time.

**Comment by PrimeTimeTran** [comment]
@feministy, yay!

**Pull request merged**
